---
- name: Deploy Docker Compose file
  hosts: localhost
  remote_user: nabarun
  become: false
  tasks:
    - name: Pull the latest musicappbackend image
      docker_image:
        name: nabaruniiitb/musicappbackend
        tag: latest
        source: pull
    - name: Start Docker Compose
      shell: docker-compose up -d
