version: '3.7'

services:
  musicapp-backend:
    image: nabaruniiitb/musicappbackend:latest
    ports:
      - "9292:9292"
    restart: always
    volumes:
      - /e/songs:/app/songs
    deploy:
      replicas: 1

